# Generated by Django 3.2.7 on 2021-12-13 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_auto_20210910_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.template', verbose_name='Шаблон'),
        ),
    ]
